name: string_tokenizer
description: A Flutter package that provides a utility method for breaking text into individual words.
version: 0.0.1
homepage: https://github.com/MixinNetwork/flutter-plugins

environment:
  sdk: ^3.5.0
  flutter: ">=3.2.0"

platforms:
  macos:
  ios:

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0

dev_dependencies:
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0